import { createElement } from 'lwc';
import LWC2ON5_ChildComponent from 'c/lWC2ON5_ChildComponent';

describe('c-l-w-c-2-o-n-5-child-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-2-o-n-5-child-component', {
            is: LWC2ON5_ChildComponent
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});